# Generated by Django 4.1.3 on 2022-11-27 20:12

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18, verbose_name='CNPJ')),
                ('lon', models.CharField(max_length=100, verbose_name='Longitude')),
                ('lat', models.CharField(max_length=100, verbose_name='Latitude')),
            ],
        ),
    ]
