# Generated by Django 4.1.3 on 2022-11-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome do Serviço')),
                ('service_create', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
