# Generated by Django 4.1.3 on 2022-11-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_cadastroservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroclientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
