# Generated by Django 4.1.3 on 2022-11-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_cadastroclientes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome')),
                ('valor', models.FloatField()),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.cadastroservico')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamentos.cadastroclientes')),
            ],
        ),
    ]
