# Generated by Django 4.1.3 on 2023-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0006_cadastroservico_remove_proposta_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='desc_prop',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='dt_servico',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Serviço'),
        ),
    ]
